language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rabinds/react-test -f ./client/Dockerfile.dev ./client

scripts:
  #- docker run -e CI=true rabinds/react-test npm test
  - docker run rabinds/react-test npm test -- --coverage

after_success:
  - docker build -t rabinds/multi-client ./client
  - docker build -t rabinds/multi-nginx ./nginx
  - docker build -t rabinds/multi-server ./server
  - docker build -t rabinds/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push rabinds/multi-client
  - docker push rabinds/multi-nginx
  - docker push rabinds/multi-server
  - docker push rabinds/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: DockerMulti-env
  bucket_name: elasticbeanstalk-us-east-2-365264456696
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY